### ISSUE TITLE
MDCC: Multi-Data Center Consistency

### ISSUE THREAD

**Issue by stonewhitener** [stonewhitener/readingss#76]
## Resources

- http://mdcc.cs.berkeley.edu/mdcc.pdf
- http://mdcc.cs.berkeley.edu/mdcc_presentation_eurosys13.pdf

## Summary

Read ommitted を保証する楽観的分散トランザクションコミットプロトコル MDCC を提案．行ごとに Generalized Paxos を実行し，トランザクションの可換性を活用しながら高速クォーラムでのコミットを試みることで，通常 1 RTT のコミット遅延を実現．2PC や Megastore と比較してコミット遅延を約 50 % 削減，ログレプリケーションのボトルネックを解消してスケーラビリティを向上．

**Comment by sirafantas** [comment]
Paxos-CP [20] improves Megastore’s replication protocol by combining non-conflicting transactions into one log-position, significantly increasing the fraction of committed transactions

**Comment by stonewhitener** [comment]
https://twitter.com/y_sira/status/1542167634484928513

**Comment by stonewhitener** [comment]
やはり TAPIR がエポックメイキングな感じある．
